using System.ComponentModel.DataAnnotations;

namespace PogoniumImporter.PokemonData
{
    public enum PokemonMove
    {
        [Display(Name = "MOVE_UNSET", Description = "Move Unset")] MoveUnset = 0,
        [Display(Name = "THUNDER_SHOCK", Description = "Thunder Shock")] ThunderShock = 1,
        [Display(Name = "QUICK_ATTACK", Description = "Quick Attack")] QuickAttack = 2,
        [Display(Name = "SCRATCH", Description = "Scratch")] Scratch = 3,
        [Display(Name = "EMBER", Description = "Ember")] Ember = 4,
        [Display(Name = "VINE_WHIP", Description = "Vine Whip")] VineWhip = 5,
        [Display(Name = "TACKLE", Description = "Tackle")] Tackle = 6,
        [Display(Name = "RAZOR_LEAF", Description = "Razor Leaf")] RazorLeaf = 7,
        [Display(Name = "TAKE_DOWN", Description = "Take Down")] TakeDown = 8,
        [Display(Name = "WATER_GUN", Description = "Water Gun")] WaterGun = 9,
        [Display(Name = "BITE", Description = "Bite")] Bite = 10,
        [Display(Name = "POUND", Description = "Pound")] Pound = 11,
        [Display(Name = "DOUBLE_SLAP", Description = "Double Slap")] DoubleSlap = 12,
        [Display(Name = "WRAP", Description = "Wrap")] Wrap = 13,
        [Display(Name = "HYPER_BEAM", Description = "Hyper Beam")] HyperBeam = 14,
        [Display(Name = "LICK", Description = "Lick")] Lick = 15,
        [Display(Name = "DARK_PULSE", Description = "Dark Pulse")] DarkPulse = 16,
        [Display(Name = "SMOG", Description = "Smog")] Smog = 17,
        [Display(Name = "SLUDGE", Description = "Sludge")] Sludge = 18,
        [Display(Name = "METAL_CLAW", Description = "Metal Claw")] MetalClaw = 19,
        [Display(Name = "VICE_GRIP", Description = "Vice Grip")] ViceGrip = 20,
        [Display(Name = "FLAME_WHEEL", Description = "Flame Wheel")] FlameWheel = 21,
        [Display(Name = "MEGAHORN", Description = "Megahorn")] Megahorn = 22,
        [Display(Name = "WING_ATTACK", Description = "Wing Attack")] WingAttack = 23,
        [Display(Name = "FLAMETHROWER", Description = "Flamethrower")] Flamethrower = 24,
        [Display(Name = "SUCKER_PUNCH", Description = "Sucker Punch")] SuckerPunch = 25,
        [Display(Name = "DIG", Description = "Dig")] Dig = 26,
        [Display(Name = "LOW_KICK", Description = "Low Kick")] LowKick = 27,
        [Display(Name = "CROSS_CHOP", Description = "Cross Chop")] CrossChop = 28,
        [Display(Name = "PSYCHO_CUT", Description = "Psycho Cut")] PsychoCut = 29,
        [Display(Name = "PSYBEAM", Description = "Psybeam")] Psybeam = 30,
        [Display(Name = "EARTHQUAKE", Description = "Earthquake")] Earthquake = 31,
        [Display(Name = "STONE_EDGE", Description = "Stone Edge")] StoneEdge = 32,
        [Display(Name = "ICE_PUNCH", Description = "Ice Punch")] IcePunch = 33,
        [Display(Name = "HEART_STAMP", Description = "Heart Stamp")] HeartStamp = 34,
        [Display(Name = "DISCHARGE", Description = "Discharge")] Discharge = 35,
        [Display(Name = "FLASH_CANNON", Description = "Flash Cannon")] FlashCannon = 36,
        [Display(Name = "PECK", Description = "Peck")] Peck = 37,
        [Display(Name = "DRILL_PECK", Description = "Drill Peck")] DrillPeck = 38,
        [Display(Name = "ICE_BEAM", Description = "Ice Beam")] IceBeam = 39,
        [Display(Name = "BLIZZARD", Description = "Blizzard")] Blizzard = 40,
        [Display(Name = "AIR_SLASH", Description = "Air Slash")] AirSlash = 41,
        [Display(Name = "HEAT_WAVE", Description = "Heat Wave")] HeatWave = 42,
        [Display(Name = "TWINEEDLE", Description = "Twineedle")] Twineedle = 43,
        [Display(Name = "POISON_JAB", Description = "Poison Jab")] PoisonJab = 44,
        [Display(Name = "AERIAL_ACE", Description = "Aerial Ace")] AerialAce = 45,
        [Display(Name = "DRILL_RUN", Description = "Drill Run")] DrillRun = 46,
        [Display(Name = "PETAL_BLIZZARD", Description = "Petal Blizzard")] PetalBlizzard = 47,
        [Display(Name = "MEGA_DRAIN", Description = "Mega Drain")] MegaDrain = 48,
        [Display(Name = "BUG_BUZZ", Description = "Bug Buzz")] BugBuzz = 49,
        [Display(Name = "POISON_FANG", Description = "Poison Fang")] PoisonFang = 50,
        [Display(Name = "NIGHT_SLASH", Description = "Night Slash")] NightSlash = 51,
        [Display(Name = "SLASH", Description = "Slash")] Slash = 52,
        [Display(Name = "BUBBLE_BEAM", Description = "Bubble Beam")] BubbleBeam = 53,
        [Display(Name = "SUBMISSION", Description = "Submission")] Submission = 54,
        [Display(Name = "KARATE_CHOP", Description = "Karate Chop")] KarateChop = 55,
        [Display(Name = "LOW_SWEEP", Description = "Low Sweep")] LowSweep = 56,
        [Display(Name = "AQUA_JET", Description = "Aqua Jet")] AquaJet = 57,
        [Display(Name = "AQUA_TAIL", Description = "Aqua Tail")] AquaTail = 58,
        [Display(Name = "SEED_BOMB", Description = "Seed Bomb")] SeedBomb = 59,
        [Display(Name = "PSYSHOCK", Description = "Psyshock")] Psyshock = 60,
        [Display(Name = "ROCK_THROW", Description = "Rock Throw")] RockThrow = 61,
        [Display(Name = "ANCIENT_POWER", Description = "Ancient Power")] AncientPower = 62,
        [Display(Name = "ROCK_TOMB", Description = "Rock Tomb")] RockTomb = 63,
        [Display(Name = "ROCK_SLIDE", Description = "Rock Slide")] RockSlide = 64,
        [Display(Name = "POWER_GEM", Description = "Power Gem")] PowerGem = 65,
        [Display(Name = "SHADOW_SNEAK", Description = "Shadow Sneak")] ShadowSneak = 66,
        [Display(Name = "SHADOW_PUNCH", Description = "Shadow Punch")] ShadowPunch = 67,
        [Display(Name = "SHADOW_CLAW", Description = "Shadow Claw")] ShadowClaw = 68,
        [Display(Name = "OMINOUS_WIND", Description = "Ominous Wind")] OminousWind = 69,
        [Display(Name = "SHADOW_BALL", Description = "Shadow Ball")] ShadowBall = 70,
        [Display(Name = "BULLET_PUNCH", Description = "Bullet Punch")] BulletPunch = 71,
        [Display(Name = "MAGNET_BOMB", Description = "Magnet Bomb")] MagnetBomb = 72,
        [Display(Name = "STEEL_WING", Description = "Steel Wing")] SteelWing = 73,
        [Display(Name = "IRON_HEAD", Description = "Iron Head")] IronHead = 74,
        [Display(Name = "PARABOLIC_CHARGE", Description = "Parabolic Charge")] ParabolicCharge = 75,
        [Display(Name = "SPARK", Description = "Spark")] Spark = 76,
        [Display(Name = "THUNDER_PUNCH", Description = "Thunder Punch")] ThunderPunch = 77,
        [Display(Name = "THUNDER", Description = "Thunder")] Thunder = 78,
        [Display(Name = "THUNDERBOLT", Description = "Thunderbolt")] Thunderbolt = 79,
        [Display(Name = "TWISTER", Description = "Twister")] Twister = 80,
        [Display(Name = "DRAGON_BREATH", Description = "Dragon Breath")] DragonBreath = 81,
        [Display(Name = "DRAGON_PULSE", Description = "Dragon Pulse")] DragonPulse = 82,
        [Display(Name = "DRAGON_CLAW", Description = "Dragon Claw")] DragonClaw = 83,
        [Display(Name = "DISARMING_VOICE", Description = "Disarming Voice")] DisarmingVoice = 84,
        [Display(Name = "DRAINING_KISS", Description = "Draining Kiss")] DrainingKiss = 85,
        [Display(Name = "DAZZLING_GLEAM", Description = "Dazzling Gleam")] DazzlingGleam = 86,
        [Display(Name = "MOONBLAST", Description = "Moonblast")] Moonblast = 87,
        [Display(Name = "PLAY_ROUGH", Description = "Play Rough")] PlayRough = 88,
        [Display(Name = "CROSS_POISON", Description = "Cross Poison")] CrossPoison = 89,
        [Display(Name = "SLUDGE_BOMB", Description = "Sludge Bomb")] SludgeBomb = 90,
        [Display(Name = "SLUDGE_WAVE", Description = "Sludge Wave")] SludgeWave = 91,
        [Display(Name = "GUNK_SHOT", Description = "Gunk Shot")] GunkShot = 92,
        [Display(Name = "MUD_SHOT", Description = "Mud Shot")] MudShot = 93,
        [Display(Name = "BONE_CLUB", Description = "Bone Club")] BoneClub = 94,
        [Display(Name = "BULLDOZE", Description = "Bulldoze")] Bulldoze = 95,
        [Display(Name = "MUD_BOMB", Description = "Mud Bomb")] MudBomb = 96,
        [Display(Name = "FURY_CUTTER", Description = "Fury Cutter")] FuryCutter = 97,
        [Display(Name = "BUG_BITE", Description = "Bug Bite")] BugBite = 98,
        [Display(Name = "SIGNAL_BEAM", Description = "Signal Beam")] SignalBeam = 99,
        [Display(Name = "X_SCISSOR", Description = "X Scissor")] XScissor = 100,
        [Display(Name = "FLAME_CHARGE", Description = "Flame Charge")] FlameCharge = 101,
        [Display(Name = "FLAME_BURST", Description = "Flame Burst")] FlameBurst = 102,
        [Display(Name = "FIRE_BLAST", Description = "Fire Blast")] FireBlast = 103,
        [Display(Name = "BRINE", Description = "Brine")] Brine = 104,
        [Display(Name = "WATER_PULSE", Description = "Water Pulse")] WaterPulse = 105,
        [Display(Name = "SCALD", Description = "Scald")] Scald = 106,
        [Display(Name = "HYDRO_PUMP", Description = "Hydro Pump")] HydroPump = 107,
        [Display(Name = "PSYCHIC", Description = "Psychic")] Psychic = 108,
        [Display(Name = "PSYSTRIKE", Description = "Psystrike")] Psystrike = 109,
        [Display(Name = "ICE_SHARD", Description = "Ice Shard")] IceShard = 110,
        [Display(Name = "ICY_WIND", Description = "Icy Wind")] IcyWind = 111,
        [Display(Name = "FROST_BREATH", Description = "Frost Breath")] FrostBreath = 112,
        [Display(Name = "ABSORB", Description = "Absorb")] Absorb = 113,
        [Display(Name = "GIGA_DRAIN", Description = "Giga Drain")] GigaDrain = 114,
        [Display(Name = "FIRE_PUNCH", Description = "Fire Punch")] FirePunch = 115,
        [Display(Name = "SOLAR_BEAM", Description = "Solar Beam")] SolarBeam = 116,
        [Display(Name = "LEAF_BLADE", Description = "Leaf Blade")] LeafBlade = 117,
        [Display(Name = "POWER_WHIP", Description = "Power Whip")] PowerWhip = 118,
        [Display(Name = "SPLASH", Description = "Splash")] Splash = 119,
        [Display(Name = "ACID", Description = "Acid")] Acid = 120,
        [Display(Name = "AIR_CUTTER", Description = "Air Cutter")] AirCutter = 121,
        [Display(Name = "HURRICANE", Description = "Hurricane")] Hurricane = 122,
        [Display(Name = "BRICK_BREAK", Description = "Brick Break")] BrickBreak = 123,
        [Display(Name = "CUT", Description = "Cut")] Cut = 124,
        [Display(Name = "SWIFT", Description = "Swift")] Swift = 125,
        [Display(Name = "HORN_ATTACK", Description = "Horn Attack")] HornAttack = 126,
        [Display(Name = "STOMP", Description = "Stomp")] Stomp = 127,
        [Display(Name = "HEADBUTT", Description = "Headbutt")] Headbutt = 128,
        [Display(Name = "HYPER_FANG", Description = "Hyper Fang")] HyperFang = 129,
        [Display(Name = "SLAM", Description = "Slam")] Slam = 130,
        [Display(Name = "BODY_SLAM", Description = "Body Slam")] BodySlam = 131,
        [Display(Name = "REST", Description = "Rest")] Rest = 132,
        [Display(Name = "STRUGGLE", Description = "Struggle")] Struggle = 133,
        [Display(Name = "SCALD", Description = "Scald")] ScaldBlastoise = 134,
        [Display(Name = "HYDRO_PUMP", Description = "Hydro Pump")] HydroPumpBlastoise = 135,
        [Display(Name = "WRAP_GREEN", Description = "Wrap Green")] WrapGreen = 136,
        [Display(Name = "WRAP_PINK", Description = "Wrap Pink")] WrapPink = 137,
        [Display(Name = "FURY_CUTTER", Description = "Fury Cutter")] FuryCutterFast = 200,
        [Display(Name = "BUG_BITE", Description = "Bug Bite")] BugBiteFast = 201,
        [Display(Name = "BITE", Description = "Bite")] BiteFast = 202,
        [Display(Name = "SUCKER_PUNCH", Description = "Sucker Punch")] SuckerPunchFast = 203,
        [Display(Name = "DRAGON_BREATH", Description = "Dragon Breath")] DragonBreathFast = 204,
        [Display(Name = "THUNDER_SHOCK", Description = "Thunder Shock")] ThunderShockFast = 205,
        [Display(Name = "SPARK", Description = "Spark")] SparkFast = 206,
        [Display(Name = "LOW_KICK", Description = "Low Kick")] LowKickFast = 207,
        [Display(Name = "KARATE_CHOP", Description = "Karate Chop")] KarateChopFast = 208,
        [Display(Name = "EMBER", Description = "Ember")] EmberFast = 209,
        [Display(Name = "WING_ATTACK", Description = "Wing Attack")] WingAttackFast = 210,
        [Display(Name = "PECK", Description = "Peck")] PeckFast = 211,
        [Display(Name = "LICK", Description = "Lick")] LickFast = 212,
        [Display(Name = "SHADOW_CLAW", Description = "Shadow Claw")] ShadowClawFast = 213,
        [Display(Name = "VINE_WHIP", Description = "Vine Whip")] VineWhipFast = 214,
        [Display(Name = "RAZOR_LEAF", Description = "Razor Leaf")] RazorLeafFast = 215,
        [Display(Name = "MUD_SHOT", Description = "Mud Shot")] MudShotFast = 216,
        [Display(Name = "ICE_SHARD", Description = "Ice Shard")] IceShardFast = 217,
        [Display(Name = "FROST_BREATH", Description = "Frost Breath")] FrostBreathFast = 218,
        [Display(Name = "QUICK_ATTACK", Description = "Quick Attack")] QuickAttackFast = 219,
        [Display(Name = "SCRATCH", Description = "Scratch")] ScratchFast = 220,
        [Display(Name = "TACKLE", Description = "Tackle")] TackleFast = 221,
        [Display(Name = "POUND", Description = "Pound")] PoundFast = 222,
        [Display(Name = "CUT", Description = "Cut")] CutFast = 223,
        [Display(Name = "POISON_JAB", Description = "Poison Jab")] PoisonJabFast = 224,
        [Display(Name = "ACID", Description = "Acid")] AcidFast = 225,
        [Display(Name = "PSYCHO_CUT", Description = "Psycho Cut")] PsychoCutFast = 226,
        [Display(Name = "ROCK_THROW", Description = "Rock Throw")] RockThrowFast = 227,
        [Display(Name = "METAL_CLAW", Description = "Metal Claw")] MetalClawFast = 228,
        [Display(Name = "BULLET_PUNCH", Description = "Bullet Punch")] BulletPunchFast = 229,
        [Display(Name = "WATER_GUN", Description = "Water Gun")] WaterGunFast = 230,
        [Display(Name = "SPLASH", Description = "Splash")] SplashFast = 231,
        [Display(Name = "WATER_GUN", Description = "Water Gun Fast Blastoise")] WaterGunFastBlastoise = 232,
        [Display(Name = "MUD_SLAP", Description = "Mud Slap")] MudSlapFast = 233,
        [Display(Name = "ZEN_HEADBUTT", Description = "Zen Headbutt")] ZenHeadbuttFast = 234,
        [Display(Name = "CONFUSION", Description = "Confusion")] ConfusionFast = 235,
        [Display(Name = "POISON_STING", Description = "Poison Sting")] PoisonStingFast = 236,
        [Display(Name = "BUBBLE", Description = "Bubble")] BubbleFast = 237,
        [Display(Name = "FEINT_ATTACK", Description = "Feint Attack")] FeintAttackFast = 238,
        [Display(Name = "STEEL_WING", Description = "Steel Wing")] SteelWingFast = 239,
        [Display(Name = "FIRE_FANG", Description = "Fire Fang")] FireFangFast = 240,
        [Display(Name = "ROCK_SMASH", Description = "Rock Smash")] RockSmashFast = 241,
        [Display(Name = "TRANSFORM", Description = "Transform")] TransformFast = 242,
        [Display(Name = "COUNTER", Description = "Counter")] CounterFast = 243,
        [Display(Name = "POWDER_SNOW", Description = "Powder Snow")] PowderSnowFast = 244,
        [Display(Name = "CLOSE_COMBAT", Description = "Close Combat")] CloseCombat = 245,
        [Display(Name = "DYNAMIC_PUNCH", Description = "Dynamic Punch")] DynamicPunch = 246,
        [Display(Name = "FOCUS_BLAST", Description = "Focus Blast")] FocusBlast = 247,
        [Display(Name = "AURORA_BEAM", Description = "Aurora Beam")] AuroraBeam = 248,
        [Display(Name = "CHARGE_BEAM", Description = "Charge Beam")] ChargeBeamFast = 249,
        [Display(Name = "VOLT_SWITCH", Description = "Volt Switch")] VoltSwitchFast = 250,
        [Display(Name = "WILD_CHARGE", Description = "Wild Charge")] WildCharge = 251,
        [Display(Name = "ZAP_CANNON", Description = "Zap Cannon")] ZapCannon = 252,
        [Display(Name = "DRAGON_TAIL", Description = "Dragon Tail")] DragonTailFast = 253,
        [Display(Name = "AVALANCHE", Description = "Avalanche")] Avalanche = 254,
        [Display(Name = "AIR_SLASH", Description = "Air Slash")] AirSlashFast = 255,
        [Display(Name = "BRAVE_BIRD", Description = "Brave Bird")] BraveBird = 256,
        [Display(Name = "SKY_ATTACK", Description = "Sky Attack")] SkyAttack = 257,
        [Display(Name = "SAND_TOMB", Description = "Sand Tomb")] SandTomb = 258,
        [Display(Name = "ROCK_BLAST", Description = "Rock Blast")] RockBlast = 259,
        [Display(Name = "INFESTATION", Description = "Infestation")] InfestationFast = 260,
        [Display(Name = "STRUGGLE_BUG", Description = "Struggle Bug")] StruggleBugFast = 261,
        [Display(Name = "SILVER_WIND", Description = "Silver Wind")] SilverWind = 262,
        [Display(Name = "ASTONISH", Description = "Astonish")] AstonishFast = 263,
        [Display(Name = "HEX", Description = "Hex")] HexFast = 264,
        [Display(Name = "NIGHT_SHADE", Description = "Night Shade")] NightShade = 265,
        [Display(Name = "IRON_TAIL", Description = "Iron Tail")] IronTailFast = 266,
        [Display(Name = "GYRO_BALL", Description = "Gyro Ball")] GyroBall = 267,
        [Display(Name = "HEAVY_SLAM", Description = "Heavy Slam")] HeavySlam = 268,
        [Display(Name = "FIRE_SPIN", Description = "Fire Spin")] FireSpinFast = 269,
        [Display(Name = "OVERHEAT", Description = "Overheat")] Overheat = 270,
        [Display(Name = "BULLET_SEED", Description = "Bullet Seed")] BulletSeedFast = 271,
        [Display(Name = "GRASS_KNOT", Description = "Grass Knot")] GrassKnot = 272,
        [Display(Name = "ENERGY_BALL", Description = "Energy Ball")] EnergyBall = 273,
        [Display(Name = "EXTRASENSORY", Description = "Extrasensory")] ExtrasensoryFast = 274,
        [Display(Name = "FUTURESIGHT", Description = "Futuresight")] Futuresight = 275,
        [Display(Name = "MIRROR_COAT", Description = "Mirror Coat")] MirrorCoat = 276,
        [Display(Name = "OUTRAGE", Description = "Outrage")] Outrage = 277,
        [Display(Name = "SNARL", Description = "Snarl")] SnarlFast = 278,
        [Display(Name = "CRUNCH", Description = "Crunch")] Crunch = 279,
        [Display(Name = "FOUL_PLAY", Description = "Foul Play")] FoulPlay = 280,
        [Display(Name = "HIDDEN_POWER", Description = "Hidden Power")] HiddenPowerFast = 281,
    }
}
